fieldLayouts:
  3f54271e-2607-4187-ac7a-4bc895b7f6cf:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: dfda25ef-e7b9-4eb5-90b8-7f919a0d2138
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ddea360f-0ff8-4853-82cd-08643c3733a1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9426cab1-2d05-4f7c-86d9-a1b1c663ec65
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'About Us'
        sortOrder: 1
handle: customerService
hasTitleField: false
name: 'Customer Service'
section: f37c649b-5dc5-46aa-b6f4-63682de70793
sortOrder: 1
titleFormat: '{section.name|raw}'
