contentColumnType: text
fieldGroup: ece0e55a-280c-4dcd-92cd-153c182a099f
handle: imageFileName
instructions: 'Do not include format. example "truck-bell" NOT "truck-bell.jpeg"'
name: 'Image File Name'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
