contentColumnType: string
fieldGroup: cb381506-e780-47c8-a8fa-e97066722b4d
handle: image
instructions: ''
name: Image
searchable: true
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:70a7bb30-1282-40bc-bd73-83702d8a3b7b'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:70a7bb30-1282-40bc-bd73-83702d8a3b7b'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
