assets:
  tempVolumeUid: 70a7bb30-1282-40bc-bd73-83702d8a3b7b
dateModified: 1608347618
email:
  fromEmail: nicholas.gill23@gmail.com
  fromName: Southpark
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  commerce:
    edition: pro
    enabled: true
    schemaVersion: 3.2.7
  commerce-authorize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  commerce-taxjar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  craftql:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 2.1.2
  freeform:
    edition: pro
    enabled: true
    schemaVersion: 3.0.8
    settings:
      ajaxByDefault: false
      autoScrollToErrors: true
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formSubmitDisable: false
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: flexbox.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: false
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: null
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaType: v2_checkbox
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      scriptInsertLocation: footer
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: false
      spamFolderEnabled: false
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
  jsonclient:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  postie:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
system:
  edition: solo
  live: true
  name: Southpark
  schemaVersion: 3.5.13
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
