enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  6594f17b-ca55-4234-bc14-b9d16f7eb45b:
    enabledByDefault: true
    hasUrls: true
    template: /
    uriFormat: __home__
type: single
